CONTENT:
  lib/templates/content
HEADER:
  lib/templates/header
EMAIL:
  lib/templates/email
WORK_FLOW:
  work_flow/
XML_CONFIG:
  config/config.xml
TEST_CASES:
  lib/test_cases/
Recording:
  lib/record/
WECHAT:
  config/wechat.yaml
LOG:
  lib/report/log/
REPORT:
  lib/report/
CASES:
  cases/
DATA:
  data/
RES:
  lib/relevant_params/
