EXTRACT_VARIABLE_TEMPLATE: 'lib/template/extract_variable_template'
CONTENT_TEMPLATE_PATH: 'lib/template/content_template'
HEADER_TEMPLATE_PATH: 'lib/template/header_template'
EMAIL_TEMPLATE_PATH: 'lib/template/email_template'
WORK_FLOW_CASE_PATH: 'workFlow_cases/'
XML_CONFIG_PATH: 'config/config.xml'
TEST_CASES_PATH: 'lib/test_cases/'
FIDDLER_CASES_PATH: 'WorkFlow/'
WECHAT: 'config/wechat.yaml'
EXTRACT_VARIABLE: 'extract_variable/'
LOG_PATH: 'report/log/'
REPORT_PATH: 'report/'
CASES_PATH: 'cases/'
DATA_PATH: 'data/'
PUBLIC_RES: 'res/'
EXTRACT: 'extract/'
