CONTENT:
  lib/templates/content
HEADER:
  lib/templates/header
EMAIL:
  lib/templates/email
WORK_FLOW:
  workFlow_cases/
XML_CONFIG:
  config/config.xml
TEST_CASES:
  lib/test_cases/
FIDDLER_CASES:
  WorkFlow/
WECHAT:
  config/wechat.yaml
LOG:
  report/log/
REPORT:
  report/
CASES:
  cases/
DATA: data/
RES:
  relevant_params/
