CONTENT_TEMPLATE_PATH: 'lib/templates/content'
HEADER_TEMPLATE_PATH: 'lib/templates/header'
EMAIL_TEMPLATE_PATH: 'lib/templates/email'
WORK_FLOW_CASE_PATH: 'workFlow_cases/'
XML_CONFIG_PATH: 'config/config.xml'
TEST_CASES_PATH: 'lib/test_cases/'
FIDDLER_CASES_PATH: 'WorkFlow/'
WECHAT: 'config/wechat.yaml'
LOG_PATH: 'report/log/'
REPORT_PATH: 'report/'
CASES_PATH: 'cases/'
DATA_PATH: 'data/'
PUBLIC_RES: 'relevant_params/'
EXTRACT: 'extract/'
